export const allChapters = [
  {
    subject: "Higher Mathematics",
    paper: "first",
    chapters: [
      "Chapter 01: Matrix and Determinant",
      "Chapter 02: Vector",
      "Chapter 03: Straight Line",
      "Chapter 04: Circle",
      "Chapter 05: Permutation and Combination",
      "Chapter 06: Trigonometric Ratios",
      "Chapter 07: Trigonometric Ratios of Compound and Composite Angles",
      "Chapter 08: Function and Graph of Functions",
      "Chapter 09: Integration",
      "Chapter 10: Differentiation",
    ],
  },
  {
    subject: "Higher Mathematics",
    paper: "second",
    chapters: [
      "Chapter 01: Real Numbers and Inequality",
      "Chapter 02: Linear Programming",
      "Chapter 03: Complex Numbers",
      "Chapter 04: Polynomial and Polynomial Equations",
      "Chapter 05: Binomial Expansion",
      "Chapter 06: Conics",
      "Chapter 07: Inverse Trigonometric Functions and Trigonometric Equations",
      "Chapter 08: Statics",
      "Chapter 09: Motion of Particles in a Straight Line or Plane",
      "Chapter 10: Measurement of Spread and Probability",
    ],
  },
  {
    subject: "Biology",
    paper: "first",
    chapters: [
      "Chapter 01: Cell and Cell Structure",
      "Chapter 02: Cell Division",
      "Chapter 03: Cell Chemistry",
      "Chapter 04: Microorganisms",
      "Chapter 05: Algae and Fungi",
      "Chapter 06: Bryophytes and Pteridophytes",
      "Chapter 07: Gymnosperms and Angiosperms",
      "Chapter 08: Tissue and Tissue Systems",
      "Chapter 09: Plant Physiology",
      "Chapter 10: Plant Reproduction",
      "Chapter 11: Biotechnology",
      "Chapter 12: Ecology, Distribution, and Conservation",
    ],
  },
  {
    subject: "Biology",
    paper: "second",
    chapters: [
      "Chapter 01: Diversity and Classification of Animals",
      "Chapter 02: Introduction to Animals",
      "Chapter 03: Human Physiology: Digestion and Absorption",
      "Chapter 04: Human Physiology: Blood and Circulation",
      "Chapter 05: Human Physiology: Respiration",
      "Chapter 06: Human Physiology: Excretion and Osmoregulation",
      "Chapter 07: Human Physiology: Movement and Locomotion",
      "Chapter 08: Human Physiology: Coordination and Control",
      "Chapter 09: Continuity of Life",
      "Chapter 10: Immunity",
      "Chapter 11: Genetics and Evolution",
      "Chapter 12: Animal Behavior",
    ],
  },
  {
    subject: "Physics",
    paper: "first",
    chapters: [
      "Chapter 01: The Physical World and Measurement",
      "Chapter 02: Vectors",
      "Chapter 03: Kinematics",
      "Chapter 04: Newtonian Mechanics",
      "Chapter 05: Work, Energy, and Power",
      "Chapter 06: Properties of Matter",
      "Chapter 07: Periodic Motion",
      "Chapter 08: Waves",
      "Chapter 09: Ideal Gases and Kinetic Theory of Gases",
    ],
  },
  {
    subject: "Physics",
    paper: "second",
    chapters: [
      "Chapter 01: Thermodynamics",
      "Chapter 02: Electrostatics",
      "Chapter 03: Current Electricity",
      "Chapter 04: Magnetic Effects of Current and Magnetism",
      "Chapter 05: Electromagnetic Induction and Alternating Current",
      "Chapter 06: Geometric Optics",
      "Chapter 07: Physical Optics",
      "Chapter 08: Introduction to Modern Physics",
      "Chapter 09: Atomic Models and Nuclear Physics",
      "Chapter 10: Semiconductors and Electronics",
      "Chapter 11: Astronomy",
    ],
  },
  {
    subject: "Statistics",
    paper: "first",
    chapters: [
      "Chapter 01: Concepts of Statistics, Variables, and Various Symbols",
      "Chapter 02: Data Collection, Summarization, and Presentation",
      "Chapter 03: Measures of Central Tendency",
      "Chapter 04: Measures of Dispersion",
      "Chapter 05: Skewness, Kurtosis, and Moments",
      "Chapter 06: Correlation and Regression",
      "Chapter 07: Time Series Analysis",
      "Chapter 08: Published Statistics of Bangladesh",
    ],
  },
  {
    subject: "Statistics",
    paper: "second",
    chapters: [
      "Chapter 01: Probability",
      "Chapter 02: Random Variables and Probability Distributions",
      "Chapter 03: Mathematical Expectation",
      "Chapter 04: Binomial Distribution",
      "Chapter 05: Poisson Distribution",
      "Chapter 06: Normal Distribution",
      "Chapter 07: Index Numbers",
      "Chapter 08: Sampling",
      "Chapter 09: Biostatistics",
    ],
  },
  {
    subject: "Chemistry",
    paper: "first",
    chapters: [
      "Chapter 01: Safe Use of Laboratory",
      "Chapter 02: Qualitative Chemistry",
      "Chapter 03: Periodic Properties of Elements and Chemical Bonding",
      "Chapter 04: Chemical Reactions",
      "Chapter 05: Applied Chemistry",
    ],
  },
  {
    subject: "Chemistry",
    paper: "second",
    chapters: [
      "Chapter 01: Environmental Chemistry",
      "Chapter 02: Organic Chemistry",
      "Chapter 03: Quantitative Chemistry",
      "Chapter 04: Electrochemistry",
      "Chapter 05: Industrial Chemistry",
    ],
  },
];

export const subjectOption = ["Higher Mathematics", "Biology", "Physics", "Statistics", "Chemistry"].map((item) => ({
  label: <span className="capitalize">{item}</span>,
  value: item,
}));
export const institutionOption = ["DU", "RU", "BSMRSTU", "CU"].map((item) => ({
  label: <span className="capitalize">{item}</span>,
  value: item,
}));
